name: Cypress Mock Regression

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run tests against mock (dev, cdt, preprod, prod, beta)"
        required: true
        default: "cdt"      

  #schedule:
    # “At minute 0 past hour 9, 12, and 15 on every day-of-week from Monday through Friday.” https://crontab.guru/#0_9,12,15_*_*_1-5
    #- cron: 0 9 15 * * 1-5

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    outputs:
      failure: ${{ steps.set-failure.outputs.status }}
    env:
      ENV_TARGET: ${{ github.event.inputs.environment }}
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4]
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up npm registry
        uses: bduff9/use-npmrc@v1.2
        with:
          dot-npmrc: ${{ secrets.NEXUS_GITHUB_NPMRC }}

      - name: Ensure defaults are set
        run: |
          if [[ -z $ENV_TARGET ]]
          then
            echo ENV_TARGET=cdt >> $GITHUB_ENV
          fi
      - uses: cypress-io/github-action@v4.2.0
        name: Cypress run       
        with:
          start: npm run test:e2e:${{ env.ENV_TARGET }}
          config-file: cypress.config.ts
          record: true
          parallel: true
          browser: chrome
          tag: env-${{ env.ENV_TARGET }}
          spec: |
            cypress/integration/features/book/end-to-end/Regression/*.feature
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_USER: ${{ secrets.CYPRESS_USER }}
          CYPRESS_PASS: ${{ secrets.CYPRESS_PASS }}
          CYPRESS_USER_EXT: ${{ secrets.CYPRESS_USER_EXT }}
          CYPRESS_PASS_EXT: ${{ secrets.CYPRESS_PASS_EXT }}
          CYPRESS_lang: en
          CYPRESS_brand: maersk
          CYPRESS_host: ${{ env.ENV_TARGET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    

      - id: set-failure
        if: failure()
        run: echo "::set-output name=status::true"

  # Send notifications is a separate job or it runs at the end of every part of the matrix job
  send-notifications:
    runs-on: ubuntu-20.04
    needs: cypress-run
    if: always()
    steps:
      - name: Teams Failure notification
        if: ${{ needs.cypress-run.outputs.failure == 'true' }}
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ms-teams-webhook-uri: ${{ secrets.TEAMS_WEBHOOK_URI }}
          notification-summary: 😢 Cypress E2E tests on ${{ env.ENV_TARGET }} have failed
          notification-color: B80012

      - name: Teams Success notification
        if: ${{ needs.cypress-run.outputs.failure != 'true' }}
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ms-teams-webhook-uri: ${{ secrets.TEAMS_WEBHOOK_URI }}
          notification-summary: 🎉 Cypress E2E tests on ${{ env.ENV_TARGET }} have passed
          notification-color: 40AB35
