name: Cypress Mock Regression

on:  
  workflow_dispatch:    
    inputs:      
      environment:        
        description: "Select the branch you want to run"
        required: true

jobs:
  cypress-run:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['18.x', '20.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node_version }}

    - uses: cypress-io/github-action@v4.2.0
        name: Cypress run       
        with:
          start: npm run cypress-dashboard
          config-file: cypress.config.js
          record: true
          parallel: true
          browser: chrome
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    

      - id: set-failure
        if: failure()
        run: echo "::set-output name=status::true"